### PR TITLE
Implement default, using the number of CPUs

### PR DESCRIPTION
**Pull request by notriddle**
Recommended in https://public.etherpad-mozilla.org/p/rust-api-guidelines-threadpool

### CODE REVIEW

**Comment by frewsxcv** [comment]
I wonder if `ThreadPool::new` shouldn't take any args and use this implementation by default. Then have some sort of builder that allows setting number of worker-threads and thread-name

**Comment by dns2utf8** [comment]
I think is a little early for two arguments. Plus it would break the API.

What do you think about a `ThreadPool::default` and a seperate `ThreadPoolBuider`?

**Comment by frewsxcv** [comment]
Relevant: https://github.com/frewsxcv/rust-threadpool/issues/77

**Comment by notriddle** [comment]
Even if we do end up setting up a builder pattern, we can always build this kind of implementation on top of it. Something like

```rust
impl Default for ThreadPool {
  fn default() -> Self {
    ThreadPoolBuilder::new().build()
  }
}
```

Just a convenience wrapper, at that point, but worth having so that others don't have to import the builder unless they actually need all those options.

**Pull request merged**
