### PR TITLE
Rename `new_with_name` to `with_name`

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by dns2utf8** [comment]
Looks good to me, similar to `Vec::with_capacity`

**Comment by frewsxcv** [comment]
thanks!

bors r+

**Comment by notriddle** [comment]
AppVeyor didn't run on the merge commit because [staging isn't in the branch whitelist](https://github.com/frewsxcv/rust-threadpool/blob/e717f05/appveyor.yml#L49).

BTW, you probably want to put "trying" in the whitelist as well, so that `bors try` works.

**Pull request merged**
