### PR TITLE
Enable `#[deprecated]` doc, requires rust 1.9

### PR DESCRIPTION
**Pull request by dns2utf8**
Rust 1.9 is stable now

### CODE REVIEW

**Comment by frewsxcv** [comment]
Minimum version in the `.travis.yml` file needs to be bumped.

**Comment by dns2utf8** [comment]
Ah, you are right. Missed that.

Would you like to release a new version or should we wait until rust 1.9 is deployed more wideley?

**Comment by frewsxcv** [comment]
> Would you like to release a new version or should we wait until rust 1.9 is deployed more wideley?

I might wait a week or two to merge this PR. I'll add a reminder for myself.

**Comment by dns2utf8** [comment]
Thank you.

I seem to have borken the build by removing this line from the before_script:
```bash
pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
```

Did it install cargo for the 1.4 build?

**Comment by frewsxcv** [comment]
travis-cargo is used to automatically generate documentation and deploy it to GitHub pages so I dont think we want to get rid of it.

https://github.com/huonw/travis-cargo

**Comment by dns2utf8** [comment]
Yes this would be a very inconvenient change.

Also I enabled the cargo cache with this PR.

Would you like to issue a hint in the README or the CHANGELOG for the new minimal version of the compiler?

**Comment by frewsxcv** [comment]
> Would you like to issue a hint in the README or the CHANGELOG for the new minimal version of the compiler?


Yep sounds good.

**Comment by dns2utf8** [comment]
Done.

I am currently thinking about the release. I see two views:

- rust 1.4 users: they see a breaking change, so the version should go to 2.0
- rust stable users: they see some new docs and a compiler hint, so the version should go to 1.3.1

Currently there seem to be only two distros providing a package for rust:
- [Arch](https://www.archlinux.org/packages/community/x86_64/rust/) currently 1.8, will be updated very soon so not a problem
- Debian currently 1.8 in testing, 1.9 should land in unstable soon
  - [Tracker](https://tracker.debian.org/pkg/rustc)
  - [Packages](https://packages.debian.org/search?keywords=rustc)

I have to rethink what way I would favor.

**Comment by kamalmarhubi** [comment]
Possibly relevant: there's an RFC for Rust version support policy for rust-lang-nursery crates. The suggested policy is current + last two stable releases. Link: https://github.com/rust-lang/rfcs/pull/1619

**Comment by frewsxcv** [comment]
> Possibly relevant: there's an RFC for Rust version support policy for rust-lang-nursery crates. The suggested policy is current + last two stable releases. Link: rust-lang/rfcs#1619

Sounds good. I'm not in a rush to merge this. Just moved my alarm to August 19th (the day after Rust 1.11.0 is planned to be released).

**Comment by frewsxcv** [comment]
1.11.0 is out. This should be good to go now. @dns2utf8 can you rebase?

**Comment by dns2utf8** [comment]
Thanks for the reminder :smile: 
Rebased and updated the CHANGES.md

**Comment by frewsxcv** [comment]
Thanks!

**Pull request merged**
