### PR TITLE
Use fmt::Formatter::debug_struct to implement fmt::Debug

### PR DESCRIPTION
**Pull request by bblancha**
Addresses #53

### CODE REVIEW

**Comment by dns2utf8** [comment]
Thank you for your PR. The error you encounter on travis is know, see #66.
My current guess is the machines running the build jobs have a higher load now compared to winter or last summer.

You can try to avoid the issue by running the `git commit --amend` command. Saving the commit again will give it a new hash and with a `git push --force` you can tell travis to try again.

**Comment by frewsxcv** [comment]
bors retry

**Comment by frewsxcv** [comment]
bors retry

**Comment by frewsxcv** [comment]
Just going to merge

**Comment by frewsxcv** [comment]
Thanks for the contribution!

**Pull request merged**
